-- MySQL Script generated by MySQL Workbench
-- Wed Mar  6 21:41:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema maxiusers
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema maxiusers
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `maxiusers` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
	`id` INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (`id`)
)
ENGINE = InnoDB;

USE `maxiusers` ;

-- -----------------------------------------------------
-- Table `maxiusers`.`type_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maxiusers`.`type_user` (
  `Id_type_user` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id_type_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `maxiusers`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maxiusers`.`person` (
  `Id_person` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NOT NULL,
  `Address` VARCHAR(50) NOT NULL,
  `Mail` VARCHAR(50) NOT NULL,
  `UserName` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(300) NOT NULL,
  `Age` DATE NOT NULL,
  `Img` VARCHAR(100) NULL,
  `type_user_Id_type_user` INT NOT NULL,
  PRIMARY KEY (`Id_person`),
  INDEX `fk_person_type_user_idx` (`type_user_Id_type_user` ASC) VISIBLE,
  CONSTRAINT `fk_person_type_user`
    FOREIGN KEY (`type_user_Id_type_user`)
    REFERENCES `maxiusers`.`type_user` (`Id_type_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
